<a href="https://colab.research.google.com/github/arashidefan/pytorch/blob/main/00.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
print(torch.__version__)

2.5.1+cu121


# 声明一个tensor
* 用``` torch.tensor（）
```创建tensor

In [ ]:
scalar = torch.tensor(7)
scalar

tensor(7)

## tensor.ndim 查看tensor维度
* 查看tensor的维度 用```tensor.ndim```  
* 0维标识一个数标量，1维表示一个轴，2维表示两个轴，以此类推，n维表示n维数组，有n个轴

In [ ]:
print(scalar.ndim)

0


## tonsor.item() 查看tensor的value

In [ ]:
scalar.item()


7

## vector 向量
* ndim为1 说明有1个轴
* tensor.shape 查看tensor的形状，有几个数表示几维；数字是几，表示该维度上有几个元素或者说该维度上的元素长度

In [ ]:
vector = torch.tensor([7,7])
print(vector)
print(vector.ndim)
print(vector.shape)

tensor([7, 7])
1
torch.Size([2])


## Matrix 矩阵


In [ ]:
MATRIX = torch.tensor([[7,8],[9,10]])
print(MATRIX)
print(MATRIX.ndim)
print(MATRIX.shape)

tensor([[ 7,  8],
        [ 9, 10]])
2
torch.Size([2, 2])


## 多维tensor

In [ ]:
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
print(TENSOR.ndim)
print(TENSOR.shape)
print(TENSOR[0][2][2])

3
torch.Size([1, 4, 3])
tensor(9)


# Random Tensor
Random tensors 是很重要的 ，在很多神经网络学习的时候，开始时神经网络的tensors全部是随机数字random numbers 然后随着学习，逐步调整这些随机数 使其能更好地represent data

* ```start with random numbers -> look up data -> update random numbers -> look up data -> update random numbers```
* torch.rand(dim0,dim1,dim2) 生成的tensor形状，0维上有dim0个元素，1维上有dim1个
元素，2维上有dim2个元素

In [ ]:
random_tensor = torch.rand(1,10,10)
print(random_tensor)

tensor([[[0.8123, 0.8353, 0.8301, 0.9017, 0.9608, 0.3950, 0.1736, 0.7415,
          0.2455, 0.9977],
         [0.1289, 0.8253, 0.7391, 0.5449, 0.9830, 0.4701, 0.1498, 0.6533,
          0.7447, 0.9171],
         [0.9889, 0.3315, 0.6492, 0.3508, 0.3195, 0.6597, 0.8085, 0.7634,
          0.2167, 0.1440],
         [0.9506, 0.1480, 0.5681, 0.9857, 0.8843, 0.8462, 0.9122, 0.8812,
          0.1530, 0.0094],
         [0.4408, 0.2195, 0.0340, 0.0406, 0.0556, 0.4034, 0.3769, 0.9419,
          0.8568, 0.4727],
         [0.2393, 0.0390, 0.2712, 0.8189, 0.5087, 0.4286, 0.1060, 0.5699,
          0.7056, 0.0970],
         [0.5695, 0.6456, 0.0554, 0.4894, 0.7391, 0.2384, 0.6833, 0.4658,
          0.9125, 0.8904],
         [0.9720, 0.1539, 0.3245, 0.1121, 0.9082, 0.5797, 0.4020, 0.2217,
          0.1621, 0.9185],
         [0.0123, 0.0347, 0.8049, 0.5916, 0.8374, 0.1660, 0.7915, 0.6895,
          0.1302, 0.1728],
         [0.9709, 0.3952, 0.1211, 0.3665, 0.1965, 0.4852, 0.6761, 0.0586,
          0.7661,

In [ ]:
print(random_tensor.ndim)
print(random_tensor.shape)

3
torch.Size([1, 10, 10])


* torch.rand(size=(x)) 生成形状维x的随机tensor

In [ ]:
random_image_size_tensor = torch.rand(size=(3,224,224))
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

# Zeros and Ones 生成value全为0或者全为1的tensor
* torch.zeros(size=(a,b)) 生成形状为[a,b]的全0tensor

In [ ]:
zero = torch.zeros(size=(4,3))
zero

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

* tensor.dtype 查看张量的数据类型 默认是float32,在pytorch中写为torch.float32

In [ ]:
zero.dtype

torch.float32

* torch.ones(size=(a,b)) 生成形状为[a,b]的全1张量


In [ ]:
one = torch.ones(size=(4,3))
one

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
one.dtype

torch.float32

# 创建range tensors
#######可以看成数组 ########
* torch.arange(start,end,step) 生成[start,end)步长为step的一个tensor数组

In [ ]:
one_to_ten = torch.arange(start=0,end=10,step=1)
one_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 如果想创建全为0或者全为1的tensor数组
* 用tensors like
* 具体实现为 torch.zeros_like(input为已经声明好形状的range)
* torch.ones_like(input)

In [ ]:
ten_zeros = torch.ones_like(input=one_to_ten)
ten_zeros

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

# Tensor datatypes 张量的数据类型
## 创建tensor时的配置选项：
 1. dtype: 返回tensor的数据类型,默认为torch.float32
 2. device: 返回tensor的数据位置，有CPU,GPU两种选择，默认为CPU
 3. requires_grid: 返回tensor是否需要记录操作来进行梯度运算，一般是False
 4. layout: 定义tensor在内存中如何存储

In [ ]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                dtype=None,
                device=None,
                requires_grad=False)
float_32_tensor.dtype,float_32_tensor.device,float_32_tensor.shape

(torch.float32, device(type='cpu'), torch.Size([3]))

## tensor.type(torch.float16) tensor的数据类型转换
* 把一个已知的Tensor type为float_32的转换成type为float16的

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor


tensor([3., 6., 9.], dtype=torch.float16)

## 在声明tensor时就可以指定其数据类型
* torch.tensor(x,dtype = y) ，x是声明的tensor ,y是它的数据类型

In [ ]:
int_32_tensor = torch.tensor([3,6,9],dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [ ]:
k = float_32_tensor * int_32_tensor
print(k.dtype)

torch.float32


# tensor.shape 与tensor.size() 是等价的

In [ ]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.5724, 0.8792, 0.4451, 0.4400],
        [0.3035, 0.6469, 0.0165, 0.0308],
        [0.3339, 0.5249, 0.2537, 0.1208]])

In [ ]:
print(some_tensor.shape)
print(some_tensor.dtype)
print(some_tensor.size())

torch.Size([3, 4])
torch.float32
torch.Size([3, 4])


# Tensor opertions include：
######tensor的操作包括加减乘除矩阵运算
* Addition   +
* Subtraction  -
* Multiplication  *
* Division  /
* Matrix multipication： tensor1.matmul(tensor2)或者torch.matmul(tensor1,tensor2)或者 torch.mm(tensor1,tensor2)


In [ ]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
tensor - 10

tensor([-9, -8, -7])

In [ ]:
tensor * 10

tensor([10, 20, 30])

In [ ]:
tensor.matmul(tensor.reshape(3,1))

tensor([14])

In [ ]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
# Matrix multiplication by hand
print(tensor, "matmul", tensor)
print(f"Equals: {torch.matmul(tensor,tensor.reshape(3,1))}") # 得到的是一个矩阵

tensor([1, 2, 3]) matmul tensor([1, 2, 3])
Equals: tensor([14])


In [ ]:
value = 0
for i in range(len(tensor)):
  value += tensor[i]*tensor[i]
print(value)

tensor(14)


In [ ]:
torch.matmul(tensor,tensor)


tensor(14)

# 深度学习中一个最常见的错误： shape errors
#### 一维向量之间的matmul 叫做点积运算，高维张量之间的matmul 叫做矩阵的乘法
#### 有两个规则在矩阵运算中需要满足：
1. @ 相当于 matmul 点积  tensor@tensor
* ```(3,2)@(3,2)``` it doesn't work
* ```(3,2)@(2,3)``` it will work

In [ ]:
torch.rand(3,2)

tensor([[0.1837, 0.3865],
        [0.2649, 0.0967],
        [0.3719, 0.9759]])

In [ ]:
torch.matmul(torch.rand(2,3),torch.rand(3,2))

tensor([[0.5605, 0.5948],
        [0.8151, 0.7847]])

## 矩阵的转置
* tensor.T

In [ ]:
# shape of matrix multiplication
tensor_A = torch.tensor([[1,2],[3,4],[5,6]])
tensor_B = torch.tensor([[7,10],[8,11],[9,12]])
torch.mm(tensor_A,tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

## tensor的形状 ```tensor.Size([8])```
###表示这个tensor是一维的，该维度下有八个数字，长度为8

In [ ]:
tensor = torch.arange(1.,9.,3)
tensor,tensor.shape

(tensor([1., 4., 7.]), torch.Size([3]))

## 更改Tensor的shape或者更改tensor的维度 且 不更改tensor的value值,有6种方法实现
* torch.reshape(input,shape)
* Tensor.view(shape)
* torch.stack(tensors,dim=0)
* torch.squeeze(input)
* torch.unsqueeze(input,shape)
* torch.permute(input,shape)

In [ ]:
import torch
x = torch.arange(1.,10)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))


### 对于x.reshape(a,b)的理解：
#### 1. 前面说的是torch.reshape(x,(a,b))的写法
#### 2. 而x.reshape(a,b)是另一种写法，将tensor X 的形状改为 两个轴，第一个轴上有a个元素，第二个轴上有b个元素，第一个轴为行 第二个轴为列 所以形状是[a,b]  ，a行b列
#### 3.任意调整张量形状，只要元素总数不变。

In [ ]:
x_reshaped = x.reshape(3,3)
x_reshaped,x_reshaped.shape
##这里的x转置之后，才是不连续存储，这时更改新的变量时，原变量的值并不会更改

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

### x.view(新的形状)
1. 同reshape类似，但要求是存储必须连续
2. 但生成的新张量与原张量共享内存，改变其中一个，另一个也跟着变化

In [ ]:
z = x.view(3,3)
z,z.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [ ]:
z[:,0] = 5
z,x

(tensor([[5., 2., 3.],
         [5., 5., 6.],
         [5., 8., 9.]]),
 tensor([5., 2., 3., 5., 5., 6., 5., 8., 9.]))

### stack方法
* torch.stack(tensor,dim=0)
* 沿新维度拼接多个张量，增加一个新维度

In [ ]:
x_stacked = torch.stack([x,x,x,x],dim=1)
x_stacked,x_stacked.shape

(tensor([[5., 5., 5., 5.],
         [2., 2., 2., 2.],
         [3., 3., 3., 3.],
         [5., 5., 5., 5.],
         [5., 5., 5., 5.],
         [6., 6., 6., 6.],
         [5., 5., 5., 5.],
         [8., 8., 8., 8.],
         [9., 9., 9., 9.]]),
 torch.Size([9, 4]))

### torch.squeeze() 降维
* 直接运行tensor.squeeze() 会自动将多余的维度压缩

In [ ]:
x_stacked = torch.tensor([[1.,2.,3.,4.,5.,6.]])

In [ ]:
print(f"Previous tensor:{x_stacked}")
print(f"Previous shape:{x_stacked.shape}")
print(f"Previous dimension:{x_stacked.ndim}")
x_squeezed = x_stacked.squeeze()
print(f"\nNew tensor:{x_squeezed}")
print(f"\nNew shape:{x_squeezed.shape}")
print(f"\nNew dimension:{x_squeezed.ndim}")

Previous tensor:tensor([[1., 2., 3., 4., 5., 6.]])
Previous shape:torch.Size([1, 6])
Previous dimension:2

New tensor:tensor([1., 2., 3., 4., 5., 6.])

New shape:torch.Size([6])

New dimension:1


### torch.unsqueeze() 升维，指定维度 dim 上插入一个大小为 1 的新维度，从而改变张量的形状。
* torch.unsqueeze(tensor,dim=0)

In [ ]:
x_stacked = torch.tensor([1.,2.,3.,4.,5.,6.])

In [ ]:
print(f"Previous tensor:{x_stacked}")
print(f"Previous shape:{x_stacked.shape}")
print(f"Previous dimension:{x_stacked.ndim}")
x_squeezed = torch.unsqueeze(x_stacked,dim=1)
print(f"\nNew tensor:{x_squeezed}")
print(f"\nNew shape:{x_squeezed.shape}")
print(f"\nNew dimension:{x_squeezed.ndim}")

Previous tensor:tensor([1., 2., 3., 4., 5., 6.])
Previous shape:torch.Size([6])
Previous dimension:1

New tensor:tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.]])

New shape:torch.Size([6, 1])

New dimension:2


### torch.permute() 调整张量维度顺序的函数。它可以按指定的顺序 重新排列张量的维度，但不改变张量的数据本身。

In [ ]:
x_reshaped = torch.rand(size=(224,224,3))
x_reshaped

In [ ]:
print(f"Previous shape: {x_reshaped.shape}")

x_permuted = x_reshaped.permute(2,0,1)

print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


# index 角标 从tensor中select数据

In [ ]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# Let's index bracket by bracket
print(f"First square bracket:\n{x[0]}")
print(f"Second square bracket: {x[0][0]}")
print(f"Third square bracket: {x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


In [ ]:
# x的第2行
x[:,1]

tensor([[4, 5, 6]])

* x[:,:,1] :代表所有，出现这个就表示一个维度，出现俩表示2维,1表示第2列
* [[]] ---> [[2,5,8]]

In [ ]:
x[:,:,1]

tensor([[2, 5, 8]])

# PyTorch tensors & NumPy
* PyTorch 和 NumPy 是 Python 中处理数值计算的两个重要库。PyTorch 提供了一些方法，使它与 NumPy 能够高效地相互转换数据类型。这种功能非常实用，因为 NumPy 是数据处理和科学计算的常用工具，而 PyTorch 更注重深度学习和 GPU 加速的应用。

* torch.from_numpy(ndarray) - NumPy array -> PyTorch tensor.
* torch.Tensor.numpy() - PyTorch tensor -> NumPy array.

In [ ]:
import torch
import numpy as np
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array).type(torch.float32)
tensor,array,tensor.dtype

(tensor([1., 2., 3., 4., 5., 6., 7.]),
 array([1., 2., 3., 4., 5., 6., 7.]),
 torch.float32)

numpy创建arange 默认是float64,如果转换成tensor 仍然会保持相同的数据类型

In [ ]:
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [ ]:
tensor = torch.ones(7)
array = tensor.numpy()
tensor,array

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
# Change the tensor, keep the array the same
tensor = tensor + 1
tensor, array

(tensor([3., 3., 3., 3., 3., 3., 3.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

# Reproducibility 让随机性可控 —— 随机种子
## 在机器学习和深度学习中，随机性广泛存在，比如：

* 初始化神经网络的权重时使用随机数。
* 随机打乱训练数据（shuffle）。
* 随机选择训练样本（比如批次训练中的 mini-batch）。
#### 虽然这种随机性是有帮助的，可以让模型更有泛化能力，但在某些情况下，我们需要结果具有可重复性，即 在相同代码、相同环境下能得到一致的结果。这就是可重复性（reproducibility）的核心思想。

#### 随机性与伪随机性
* 随机性（Randomness）：
 计算机实际上无法生成真正的随机数，它们通过特定算法生成伪随机数（Pseudorandom numbers），基于给定的初始种子（seed）。
* 伪随机性（Pseudorandomness）：
如果设置相同的随机种子，计算机生成的随机数序列是可预测和可重复的。
在深度学习中，我们利用伪随机性来确保实验的可重复性。

In [ ]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.7854, 0.6675, 0.6544, 0.0291],
        [0.7702, 0.0981, 0.4934, 0.0658],
        [0.4038, 0.4774, 0.5587, 0.6329]])

Tensor B:
tensor([[0.7071, 0.3599, 0.2030, 0.5473],
        [0.8521, 0.8881, 0.7134, 0.7750],
        [0.3521, 0.7084, 0.2888, 0.3006]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

##### 像上面随机生成两个形状一样的tensor 它们的值是不一样的
## 因此引入torch.manual_seed(seed) 随机生成种子

In [ ]:
import torch
import random
RANDOM_SEED=42
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(seed=RANDOM_SEED) # try commenting this line out and seeing what happens
random_tensor_D = torch.rand(3, 4)


print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [ ]:
import torch
import random

# # Set the random seed
RANDOM_SEED=42 # try changing this to different values and see what happens to the numbers below
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

# Have to reset the seed every time a new rand() is called
# Without this, tensor_D would be different to tensor_C
torch.random.manual_seed(seed=RANDOM_SEED) # try commenting this line out and seeing what happens
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

# 获取GPU

In [ ]:
!nvidia-smi

Mon Dec 23 10:49:56 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   37C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

## 检查GPU是否有 pytorch

In [ ]:
import torch
torch.cuda.is_available()

True

## 设置代码运行时用GPU还是CPU

In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

## 检查有多少个gpu

In [ ]:
torch.cuda.device_count()

1

## 用GPU计算tensor

In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"
tensor = torch.tensor([1,2,3])
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

## 将运行在GPU上的tensor back to CPU
* numpy 在CPU上运行

In [ ]:
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])